name: naru
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - numpy=1.15.0
  - python=3.6
  - pip
  - pip:
    - pandas==0.24.1
    - torch==1.10.2
    - torchvision==0.11.3
    - scipy==1.2.0
